@echo off
echo Starting OS Simulation (React Version)...
cd os-sim-react
echo Installing dependencies (if needed)...
call npm install
echo Starting Development Server...
call npm run dev
pause
